name: Create SBOM
on:
  push:
  
jobs:
  create-sbom:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Microsoft SBOM tool
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https
        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/microsoft.list'
        sudo apt-get update
        sudo apt-get install -y sbom
    - name: Create SBOM
      run: sbom --json > sbom.json
    - name: Upload SBOM to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: sbom
        path: sbom.json
