name: Generate SBOM

on:
  push:
    branches:
      - main

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Microsoft SBOM tool
      run: |
        wget https://github.com/Microsoft/sarif-sdk/releases/download/v3.1.0/Microsoft.Sarif.SDK.3.1.0.nupkg
        unzip Microsoft.Sarif.SDK.3.1.0.nupkg
        sudo mv Microsoft.Sarif.SDK.3.1.0/tools/SBOM /usr/local/bin/sbom
        chmod +x /usr/local/bin/sbom

    - name: Generate SBOM
      run: sbom generate -o sbom.json

    - name: Commit and push SBOM
      run: |
        git config --local user.email "github-actions@example.com"
        git config --local user.name "GitHub Actions"
        git add sbom.json
        git commit -m "Generate SBOM"
        git push origin main

