name: Create SBOM
on:
  push:
    branches:
      - master
jobs:
  create-sbom:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Microsoft SBOM tool
      run: |
        choco install sbom
    - name: Create SBOM
      run: sbom --json > sbom.json
    - name: Upload SBOM to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: sbom
        path: sbom.json
